### ISSUE TITLE
Requirements not working

### ISSUE THREAD

**Issue by versae** [ajgallego/document-image-binarization#10]
Hi,

Congrats on the work! I read the paper since I am involved in a mass digitization process right now and I have found that binarization has a huge impact on how well OCR performs. I was trying to put this project to work although it's a bit dated. I set up a virtualenv using Python 3.7.5 and installed the dependencies. Tensorflow 1.x is now deprecated so I had to install it using the [1.15.5 wheel in PyPI](https://pypi.org/project/tensorflow/1.15.5/). I also tried several versions of Keras but none worked. Is there a way to make it work so I can use the `binarize` CLI to test my use case?

Thanks!

**Comment by ajgallego** [comment]
Dear @versae, 

Sorry for the late reply.

In the project folder you have the files requirements.txt and requirements_demo.txt to install the requirements for training and for the demo, respectively. Within your virtual environment you can install them using:

pip install -r requirements.txt

The code has been tested with Python 2.7 and Python 3. In the root folder, you also have the "setup.py" script that installs all the code. 

Kind regards

**Comment by versae** [comment]
Hi,

Thanks for the reply :)

I tried both requirements files but none worked. That's why I was wondering
if you could give me the exact versions you may have locally installed so I
can reproduce the venv and make it work.

Cheers.

--
Sent using a cell-phone, so sorry for the typos and wrong auto-corrections.

**Comment by ajgallego** [comment]
Hi, 

You can find the exact versions of the dependencies in an older version of the requirements file: 

https://github.com/ajgallego/document-image-binarization/blob/646fb5277112fd9b04fd317d29398dca2a5287b8/requirements.txt

Cheers

**Comment by versae** [comment]
Awesome, thank you!
