### ISSUE TITLE
what method/tool you use for data augmentation

### ISSUE THREAD

**Issue by erickpaulus** [ajgallego/document-image-binarization#11]
you have made a great job on binarization task. I would like to know more regarding the data augmentation technique you told in your paper. Because I can not find it in your code. Thanks a lot

**Comment by ajgallego** [comment]
Hi,

The data augmentation process was done offline. That is, we first pre-computed a series of augmented images that were added to the training set.

In the parameters of the script "train.py", you can find the option "--aug" to load an additional folder (prefixed with "aug_") to be added to the training set.

The augmentations that we made were: horizontal and vertical flips, zoom, and small rotations. It is important that you also apply the same transformations to the ground truth images and that you follow the same naming pattern explained for the training images. 

Kind regards
