### ISSUE TITLE
run_th_test method not found

### ISSUE THREAD

**Issue by wellescastro** [ajgallego/document-image-binarization#2]
Hi! Great work!

Could you tell me what the "run_th_test" method is about? I couldn't find it.

I suppose this is the method which makes the reconstruction of the image patches after forwarding them through the network and thresholding the output activation map and maybe compute the f-measure/ pseudo f-measure score using the whole image.

Thanks in advance,
Dayvid

**Comment by ajgallego** [comment]
Hi @wellescastro, thank you!

Sorry, I forgot to remove that method. I already removed it.

Initially we used our own evaluation function but in the end we changed it to use the metrics provided by Dibco, which you can find here:

http://vc.ee.duth.gr/h-dibco2016/benchmark/

Sorry for the delay in answering but I had not noticed this ticket.

Greetings
Javi
