### ISSUE TITLE
During testing best threshold is not set

### ISSUE THREAD

**Issue by didirus** [ajgallego/document-image-binarization#3]
Thank you for open-sourcing this! 

When I run the script with --test, the best threshold is not set and uses default value -1. How to know the threshold with a pre-trained model?

**Comment by ajgallego** [comment]
Hi @didirus, thank you for your interest in our work.

The threshold used for the weights provided was 0.5. This is explained in the related publication:

https://www.sciencedirect.com/science/article/pii/S0031320318303091

Greetings!
