### ISSUE TITLE
threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

### ISSUE THREAD

**Issue by CognitiveClouds-Prasad** [ajgallego/document-image-binarization#5]
python document-image-binarization/binarize.py -imgpath x.jpg -modelpath MODELS/model_weights_dibco_6_256x256_s96_aug_m205_f64_k5_s2_se3_e200_b32_esp.h5 -w 256 -s 96 -f 64 -k 5 -stride 2 -th 0.5 --demo
Using TensorFlow backend.
Traceback (most recent call last):
  File "document-image-binarization/binarize.py", line 12, in <module>
    util.init()
  File "/home/x/x/x/document-image-binarization/util.py", line 14, in init
    np.set_printoptions(threshold=np.nan) 
  File "/home/x/.local/lib/python2.7/site-packages/numpy/core/arrayprint.py", line 246, in set_printoptions
    floatmode, legacy)
  File "/home/x/.local/lib/python2.7/site-packages/numpy/core/arrayprint.py", line 93, in _make_options_dict
    raise ValueError("threshold must be numeric and non-NAN, try "
ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

I have been unable to run this application.

**Comment by VisualFox** [comment]
@line 14 in util.py replace:
np.set_printoptions(threshold=np.nan)
by
np.set_printoptions(threshold=sys.maxsize)

I am going to work on a patch

and finally If you are running with python3 you also need to replace xrange by range in utilModelREDNet.py and utilDataGenerator.py

**Comment by ajgallego** [comment]
Thanks @VisualFox, I close this issue since it has been fixed by @VisualFox.

**Comment by CognitiveClouds-Prasad** [comment]
Thanks @VisualFox :slightly_smiling_face: I will try it out today or in sometime. I will reply back on this thread if there are issues.

**Comment by CognitiveClouds-Prasad** [comment]
This is working beautifully! Thanks @ajgallego and @VisualFox :slightly_smiling_face:
