### ISSUE TITLE
packaging

### ISSUE THREAD

**Issue by bertsky** [ajgallego/document-image-binarization#9]
This looks interesting. Could you please provide information on installation / requirements, or a proper setup.py for release on PyPI?

**Comment by ajgallego** [comment]
Dear bertsky, thanks for your interest.

I have added the requirements file. What other things would you need? Do you have any example of the setup.py file?

We are interested in releasing the code in PyPI, so if necessary, some more changes could be made in order to adapt the code.

**Comment by bertsky** [comment]
@ajgallego splendid!

Ideally, the `requirements.txt` is referenced by a `setup.py` conforming to [Python packaging guidelines](https://packaging.python.org/tutorials/installing-packages/). Together this effectively can take care of the distribution and installation of your package.

To maximize utilty for other users, it's also necessary to minimize the assumptions/constraints of your requirements. Currently, that list requires the exact version you happened to have installed when you did `pip freeze` – but your actual requirements wlll almost always be broader. Also, it's not necessary to list dependent packages there. E.g. instead of ...

```
tensorboard==1.15.0
tensorflow-estimator==1.15.1
tensorflow-gpu==1.15.0
```

...you could probably just write `tensorflow<2.0`. – In this case, I know that since 1.15 TF deprecates the use of the package name variant with `gpu` in it, and they have unified everything in 2.0 anyway. But the API changes (you'd have to [migrate](https://www.tensorflow.org/guide/migrate) your code) and the ABI too (you'd have to retrain your models), so I am guessing you'd want to stick before TF2 for now. The others are pulled in automatically.

Also, try to remove entries completely which you don't really need, like e.g. `Keras-Applications==1.0.8 Keras-Preprocessing==1.1.0` (again I'm just guessing).

For an example of a setup.py see [here](https://github.com/ASVLeipzig/cor-asv-ann/blob/master/setup.py) or [here](https://github.com/OCR-D/ocrd_tesserocr/blob/master/setup.py).

**Comment by ajgallego** [comment]
@bertsky, thanks for the clarifications. I have updated the requirements file following your instructions and added the "setup.py" file.

Let me know if everything is fine or if you need anything else.

**Comment by bertsky** [comment]
> I have updated the requirements file following your instructions and added the "setup.py" file.

Thanks! That's nearly perfect. 2 more things could be improved:

> Installs two executables:
>    - binarize
>    - train

That's not in fact the case. You need to use the `entry_points` mechanism to make your two scripts available as CLI executables.

> opencv-python==4.*

Consider replacing `opencv-python` by `opencv-python-headless` (since the latter variant does not drag in libX* system dependencies).

**Comment by ajgallego** [comment]
> Consider replacing opencv-python by opencv-python-headless (since the latter variant does not drag in libX* system dependencies).

I have updated the requirements file to replace this dependency. However, this produces an error when I run the binarizer demo version (`--demo`). The demo opens a window, so it request the `libgtk2.0-dev` library. To validate this I've created a new virtual environment and installed only the dependencies listed in requirements.txt. 

> That's not in fact the case. You need to use the entry_points mechanism to make your two scripts available as CLI executables.

I've modified the setup file to add the `entry_points`. For this I had to define a package. I hope it's fine now. I tried to install it and it seems that everything works fine.

**Comment by bertsky** [comment]
> I've modified the setup file to add the `entry_points`. For this I had to define a package. I hope it's fine now. I tried to install it and it seems that everything works fine.

Excellent!

> However, this produces an error when I run the binarizer demo version (`--demo`). The demo opens a window, so it request the `libgtk2.0-dev` library. To validate this I've created a new virtual environment and installed only the dependencies listed in requirements.txt.

Yes, sorry, I have not thought about that repercussion. The demo is fascinating, you can see the sliding window in action. But maybe you want to separate this functionality from normal behaviour to keep dependencies minimal? One thing you could do is move the dependency on the OpenCV variant which includes X11 dependencies into an optional feature of your package:

```Python
    extras_require={
        'demo': ['opencv-python==4.*]
    },
```

That would cause normal installation via `pip install document-image-binarization` use the headless variant only, but `pip install document-image-binarization[demo]` install the full version.

On top of that, to still give the user a better experience than running into the `cv2.error` about Windows/GTK/Cocoa support, you could then either

1. catch the exceptions around the `cv2.namedWindow` and `cv2.imshow` lines, giving a warning which hints to the installation feature `demo`, or even

2. move the entire demo to a separate entry point `demo()` instead of `main()` which only gets installed along with the demo feature:
```Python
    entry_points={
        'console_scripts': [
            'binarize = binarize.binarize:main',
            'binarize-demo = binarize.binarize:demo[demo]',
            'train_binarizer = binarize.train:main',
        ],
    },
```

**Comment by ajgallego** [comment]
I have added all your suggestions: the new `extras_require`, the try-catch of `cv2.namedWindow` and `cv2.imshow`, and the new `binarize-demo` entry point. 

Let me know if everything is fine or if you need anything else.

**Comment by bertsky** [comment]
Marvellous, thank you!
